services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
  flood-db:
    image: mysql:latest
    container_name: flood-db
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=floodDatabase
      - MYSQL_USER=floodUser
      - MYSQL_PASSWORD=floodPassword
    volumes:
      - ./flood_init.sql:/data/application/init.sql
