services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
  flood-db:
    image: mysql:8.4
    container_name: flood-db
    command: mysqld --mysql-native-password=ON
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=floodDatabase
      - MYSQL_USER=floodUser
      - MYSQL_PASSWORD=floodPassword
    volumes:
      - ./flood_small_init.sql:/docker-entrypoint-initdb.d/init.sql

